### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by zhangqian001** [khawar-islam/FPVT_BMVC22#2]
Thank you very much for your excelent work. I want to know, did you have RaFD datasets, because although i ask dataset for official website, but i didnot get access, if you can send RaFD datasets to me, i will appreciate with you so much, thank you. I look forward to your letter.

**Comment by khawar-islam** [comment]
@zhangqian001 Sorry, I don't have RaFD dataset

**Comment by NIKHILDUGAR** [comment]
can you share the drive link for TALFW?

**Comment by khawar-islam** [comment]
@NIKHILDUGAR  this is .bin of TALFW

https://drive.google.com/file/d/1hNNi3iz_w0MtYD1vvLDz4Ieq7tzkSQ82/view
