### ISSUE TITLE
how to create .bin file for testing of your model

### ISSUE THREAD

**Issue by Mohsin849** [khawar-islam/FPVT_BMVC22#3]
Dear Islam,
Hopefully, you are good.
I just want to test your model on other aging datasets. But unable to create .bin file that will work successfully. I need the FGNET dataset .bin file. I need your help regarding this. 
Early response will be highly obliged. 
Thanks

**Comment by khawar-islam** [comment]
Dear @Mohsin849 

You can search on issue section where you can easily find how to create .bin file.
https://github.com/ZhaoJ9014/face.evoLVe

Regards,
Khawar

**Comment by Mohsin849** [comment]
Dear @khawar-islam 
I thoroughly visit the link mentioned above. But I cannot find the method to convert the dataset into .bin file. It is requested that please help me regarding this as I can test your model on other datasets by converting those into .bin file.
I have already found issues generated by you on other repo to find the same answer. That's why I am pretty sure that you must have a solution for this. Because you did the same work. 
Thanks & Regards
Mohsin Sharif

**Comment by khawar-islam** [comment]
Dear @Mohsin849 

Please check in below link and you can easily find on issue section and I did not test on FGNET dataset.
https://github.com/deepinsight/insightface/issues?q=bin+

**Comment by Mohsin849** [comment]
Dear @khawar-islam 
Thanks for your effort. I find out a way to create .bin file. 
Thanks & Regards
Mohsin Sharif
