### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by Mohsin849** [khawar-islam/FPVT_BMVC22#4]
Hello @khawar-islam 
Hopefully, You are good. Actually, I am trying to implement this project on my local machine. But unfortunately, I am facing errors regarding requirements.txt. Can you please tell me which python version is compatible with this project? 
Thanks & Regards
Mohsin Sharif

**Comment by khawar-islam** [comment]
Hi @Mohsin849 

Python 3.7 would be fine for FPVT.

**Comment by Mohsin849** [comment]
Thanks @khawar-islam
